### PR TITLE
Improve 'bought' Function to Stop Direct Payment to Seller #3

### PR DESCRIPTION
**Pull request by Dishant-garg**
Solved issue #3
Made the function payable to accept ether.
Screenshot (439)

### CODE REVIEW

**Comment by Dishant-garg** [comment]
@TechWizard9999 pls review the pr

**Comment by Dishant-garg** [comment]
i have done two commits as previous commit didn't show my changes in file pls see final solved issue commit

**Comment by TechWizard9999** [comment]
@Dishant-garg 
Actually, there is an error in your code. Please review it and then submit a PR again

**Comment by Dishant-garg** [comment]
@TechWizard9999 now review the code pls

**Comment by TechWizard9999** [comment]
@Dishant-garg 
Nice work!! Keep it up!

**Pull request closed without merging**
