### PR TITLE
feat: Integrate ethers.js for Sepolia network connection resolve #5

### PR DESCRIPTION
**Pull request by vishal18713**
#5 => Refactored the code to use ethers.js for connecting to the Sepolia network, following the Ether.js documentation. Replaced hardhat's ethers import with a separate ethers import. Updated contract deployment and interaction logic accordingly. The script now successfully connects to the Sepolia network and deploys contracts using the specified gas price. Import the ethrs.js for the RpcProvider function and also used hardhat for the use of the getContractFactory function.
image

realEstate address: 0x5FbDB2315678afecb367f032d93F642f64180aa3
Contract address: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512

### CODE REVIEW

**Comment by vishal18713** [comment]
@TechWizard9999 
kindly review my code.

**Comment by TechWizard9999** [comment]
@vishal18713 
 Keep your API key in the .env file and use it in the code.

**Comment by vishal18713** [comment]
@TechWizard9999 
I have added the API key to the .env file review it once.

**Comment by TechWizard9999** [comment]
@vishal18713 
Nice work!! but make sure from the next project you keep the api key in the process.env not the whole Api

**Pull request closed without merging**
