### PR TITLE
Simplified cancelSale function Resolved #7 

### PR DESCRIPTION
**Pull request by Dishant-garg**
Solved issue #7 
I enhanced the cancel sale function by adding functionalities like that only the seller or the buyer can cancel the sale, check if the property is listed for sale before proceeding and if the buyer initiated the cancellation, we refund the purchase price to the seller.
Screenshot (442)
 @TechWizard9999 pls review the pr

### CODE REVIEW

**Comment by TechWizard9999** [comment]
@Dishant-garg 
Make sure it says or shows that the cancellation worked

**Comment by Dishant-garg** [comment]
@TechWizard9999 now pls review the pr again

**Comment by Dishant-garg** [comment]
@TechWizard9999 pls review the changes if needed for changes then pls tell me

**Comment by TechWizard9999** [comment]
@Dishant-garg 
Your code still lacks if the cancellation function has been executed or not
Once check the function and PR the changes

**Comment by Dishant-garg** [comment]
@TechWizard9999 resolved the issue again now check if the function is fulfilling all the needs according to pr or not

**Comment by TechWizard9999** [comment]
@Dishant-garg 
Nice work !! But make sure to use emit functions for teh gas optimisation

**Pull request closed without merging**
