### PR TITLE
Resolved direct payment to seller in bought function Resolved #3

### PR DESCRIPTION
**Pull request by vishal18713**
#3 => To make a function ready for transaction it must be mentioned as payable . For it's enhancement , the require tag is used so as to check whether the transfer to seller is successful or not then the transfer of the NFT( referring to that property) is done and finally the property token is removed from the property sale list.

### CODE REVIEW

**Comment by TechWizard9999** [comment]
@vishal18713 
There is still error in your code 
Re-Check it and create an another PR

**Comment by vishal18713** [comment]
> @vishal18713 There is still error in your code Re-Check it and create an another PR

@TechWizard9999 i have tried to fix the error, please review once.

**Comment by TechWizard9999** [comment]
@vishal18713 
In your code, ensure correct syntax for the 'require' statement and use the declared variables. Your logic seems perfect however, utilize the variables you have declared

**Comment by vishal18713** [comment]
@TechWizard9999 
This commit rectifies the bought function within the contract, ensuring accurate variable usage and syntax in the required statement. The purchasePrice[_nftID] variable is now properly utilized to validate the transaction amount against the designated purchase price. Additionally, the logic for transferring the balance to the sellerAddress has been adjusted to use the declared sellerAddress variable and verify the success of the transfer operation. These changes enhance code readability and maintain correctness.

**Comment by TechWizard9999** [comment]
@vishal18713 
Nice work!! Always make sure that to add payable function

**Pull request closed without merging**
