### PR TITLE
Improve 'bought' Function to Stop Direct Payment to Seller #3

### PR DESCRIPTION
**Pull request by Ansh-Agrawal1817**
Resolved #3
Made the function payable to accept ether.
Added functionality to send funds to the contract(user) instead of the seller.
Screenshot 2024-03-15 at 7 02 59 PM

### CODE REVIEW

**Comment by Ansh-Agrawal1817** [comment]
made the function payable to accept ether.
transferred the funds to contract instead of seller.

**Comment by TechWizard9999** [comment]
@Ansh-Agrawal1817 
There is still error in your code
Please re-check it

**Comment by Ansh-Agrawal1817** [comment]
The require tag is used so as to check whether the transfer to seller is successful or not.
The transfer of the NFT is done and finally the property token is removed from the property sale list.

**Comment by Ansh-Agrawal1817** [comment]
Screenshot 2024-03-16 at 2 55 17 PM

**Comment by TechWizard9999** [comment]
@Ansh-Agrawal1817 
But the code doesnt correct the logic , To be precise the seller is not payable

**Comment by Ansh-Agrawal1817** [comment]
@TechWizard9999 
Kindly review it now.
Screenshot 2024-03-16 at 11 49 29 PM

**Comment by TechWizard9999** [comment]
@Ansh-Agrawal1817 
Nice one!! Always make sure to have payable....

**Pull request closed without merging**
